### PR TITLE
fix: fix processor index/nonce conflation and add per-replica nonce storage

### LINKED ISSUE #851: bug: Replica processors share the same key for storing per-replica nonces

### PR DESCRIPTION
**Pull request by ltchang2019**
Bug: multiple `Replica` processors were sharing the same key for storing their latest inspected nonces
Changes:
-  key latest nonces by replica domain
- improve docs for pub db store functions
- Processor `IntGaugeVec` tracks Replica processor next_nonces
- standardize on `leaf` and remove all refs to `leaf_hash`

Closes #851

### CODE REVIEW

File: rust/agents/processor/src/processor.rs [hunk 1]
```diff
@@ -267,7 +262,7 @@ impl Processor {
             .new_int_gauge(
                 "next_message_index",
                 "Index of the next message to inspect",
-                &["replica", "agent"],
+                &["home", "agent"],
```
Comment (ltchang2019) [inline rust/agents/processor/src/processor.rs:265]: I only understand these prometheus objects at a very surface level but this `IntGaugeVec` doesn't look like it's getting used anywhere. @prestwich did we just forget to actually track/update this one?

File: rust/optics-core/src/db/home_db.rs [hunk 2]
```diff
@@ -235,6 +263,9 @@ impl HomeDB {
     }
 
     /// Store a proof by its leaf index
+    ///
+    /// Keys --> Values:
+    /// - `leaf_index` --> `proof`
     pub fn store_proof(&self, leaf_index: u32, proof: &Proof) -> Result<(), DbError> {
         debug!(leaf_index, "storing proof in DB");
         self.store_keyed_encodable(PROOF, &leaf_index, proof)
```
Comment (ltchang2019) [inline rust/optics-core/src/db/home_db.rs:271]: I'm confused, are these _all caps_ prefixes supposed to describe the key or the value? It looks like most cases describe the key but its inconsistent everywhere... should consolidate to standard

**Review by emberian — DISMISSED** [review]

File: rust/agents/processor/src/processor.rs (hunk 1 above)
Comment (prestwich) [reply rust/agents/processor/src/processor.rs:265]: so the `&[&str]` here is identifiers for groups of "labels" on the data. It should probably be `&["home", "replica", "agent"]` for this group of metrics. and then when we make a specific metric

Each metric is updated on L78 in the processor 

```
                self.next_nonce
                    .with_label_values(&[self.replica.name(), AGENT_NAME])
                    .set(next_nonce as i64);
```

File: rust/optics-core/src/db/home_db.rs (hunk 2 above)
Comment (prestwich) [reply rust/optics-core/src/db/home_db.rs:271]: I think they should describe the value. Feel free to change to make consistent

File: rust/agents/processor/src/processor.rs (hunk 1 above)
Comment (prestwich) [reply rust/agents/processor/src/processor.rs:265]: if updating the label array, also update the `with_label_values` invocation

File: rust/agents/processor/src/processor.rs [hunk 3]
```diff
@@ -314,20 +310,26 @@ impl OpticsAgent for Processor {
...
         let denied = self.denied.clone();
 
-        let next_message_index = self.next_message_index.clone();
-
         tokio::spawn(async move {
             let replica = replica_opt.ok_or_else(|| eyre!("No replica named {}", name))?;
             let home_name = home.name().to_owned();
 
+            let next_nonce = metrics
+                .new_int_gauge(
```
Comment (prestwich) [inline rust/agents/processor/src/processor.rs:318]: instead of making a new one, put the one on the `Processor` into an arc (and rename it appropriately), and give the arc to each replica processor struct. then have each replica processor set given its labels.

So no metric for `next_message_index` and a shared `Arc<IntGaugeVec>` for `next_nonce`

File: rust/optics-core/src/db/typed_db.rs [hunk 4]
```diff
@@ -28,6 +28,7 @@ impl TypedDB {
     fn full_prefix(&self, prefix: impl AsRef<[u8]>) -> Vec<u8> {
         let mut full_prefix = vec![];
         full_prefix.extend(self.type_prefix.as_ref() as &[u8]);
+        full_prefix.extend("_".as_bytes());
```
Comment (prestwich) [inline rust/optics-core/src/db/typed_db.rs:31]: this will cause a complete DB resync right? cc @yourbuddyconner

Comment (ltchang2019) [reply rust/optics-core/src/db/typed_db.rs:31]: Yes this will require us to scrap the existing db

**Review by prestwich — CHANGES_REQUESTED** [review]
metrics update

File: rust/optics-core/src/db/typed_db.rs (hunk 4 above)
Comment (ltchang2019) [reply rust/optics-core/src/db/typed_db.rs:31]: Either way the key prefix changes will make us do this

Comment (prestwich) [reply rust/optics-core/src/db/typed_db.rs:31]: yeah, just need to give conner a headsup when we do this. it's still relatively cheap, so no real downside but better to know than not know

**Review by prestwich — APPROVED** [review]
