### PR TITLE
fix: fix kathy sync bug related to `ethers-rs` concurrency

### LINKED ISSUE #857: bug: kathy nonce collision
I was debugging with @ltchang2019 and believe I have a hypothesis for why Kathy is crash-looping. 

When booting, kathy spawns N tasks, each responsible for dispatching messages to a particular configured replica. Issues arise when each task tries to dispatch a message at the same time or close together, because the individual tasks attempt to use the same account Nonce. 

I believe this might necessitate a fix at the ethers-rs level. 

CC @prestwich for thoughts.

### PR DESCRIPTION
**Pull request by ltchang2019**
- add lock to kathy and have her acquire and hold for duration of `home.dispatch(...).await` calls to ensure only one dispatch call happening at one time (temp fix to ether-rs concurrency bug)
- lock does not wrap home because that would require changing `AgentCore` setup

Closes #857

### CODE REVIEW

File: rust/agents/kathy/src/kathy.rs [hunk 1]
```diff
@@ -86,13 +87,19 @@ impl OpticsAgent for Kathy {
                             destination = message.destination,
                             recipient = message.recipient
                         );
+
+                        let _guard = home_lock.lock().await;
                         home.dispatch(&message).await?;
+
+                        // Drop home_lock after dispatch
```
Comment (prestwich) [inline rust/agents/kathy/src/kathy.rs:94]: drop `_guard`

**Review by prestwich — CHANGES_REQUESTED** [review]
comment nit

**Review by prestwich — APPROVED** [review]
