### PR TITLE
test/bug: verify Rust/Solidity OpticsMessage and leaf equivalence

### LINKED ISSUE #360: test: verify Rust/Solidity messages match

### PR DESCRIPTION
**Pull request by ltchang2019**
- `OpticsMessage` leaf was being incorrectly computed in Rust due to mismatch in field ordering + missing body in `write_to` method
- fixes bug and adds test to `Message.test.js` to cross-check Rust/Solidity message and leaf
- renames `StampedMessage` `OpticsMessage`

Closes #360

### CODE REVIEW

File: rust/optics-core/src/lib.rs [hunk 1]
```diff
@@ -224,21 +227,22 @@ pub struct Message {
...
     {
         writer.write_all(&self.origin.to_be_bytes())?;
         writer.write_all(self.sender.as_ref())?;
+        writer.write_all(&self.sequence.to_be_bytes())?;
         writer.write_all(&self.destination.to_be_bytes())?;
         writer.write_all(self.recipient.as_ref())?;
-        writer.write_all(&self.sequence.to_be_bytes())?;
-        Ok(36 + 36 + 4 + self.body.len())
+        writer.write_all(&self.body)?;
+        Ok(OPTICS_MESSAGE_PREFIX_LEN + self.body.len())
```
Comment (ltchang2019) [inline rust/optics-core/src/lib.rs:241]: Body was also previously not being written into output

File: rust/optics-core/src/lib.rs [hunk 2]
```diff
@@ -272,12 +276,12 @@ impl Decode for StampedMessage {
...
-impl StampedMessage {
+impl OpticsMessage {
     /// Convert the message to a leaf
     pub fn to_leaf(&self) -> H256 {
-        let mut k = Keccak256::new();
-        self.write_to(&mut k).expect("!write");
-        H256::from_slice(k.finalize().as_slice())
+        let mut buf = vec![];
+        self.write_to(&mut buf).expect("!write");
+        keccak256(buf).into()
```
Comment (ltchang2019) [inline rust/optics-core/src/lib.rs:284]: Changed to use existing `keccak256` in `ethers-rs`

**Review by ErinHales — APPROVED** [review]
🙌
